Algoritmo EJERCICIO_CONDICIONAL3
	
	DEFINIR TEMPERATURA Como Entero
	
	ESCRIBIR "INDIQUE LA TEMPERATURA ACTUAL: "
	LEER TEMPERATURA
	
	SI TEMPERATURA <18 Entonces
		ESCRIBIR "TEMPERATURA FUERA DEL RANGO DESEADO"
	SiNo
		SI TEMPERATURA >= 18 Y TEMPERATURA  <= 25
			Escribir "TEMPERATURA ADECUADA"
		SiNo
			SI TEMPERATURA >25 Entonces
				ESCRIBIR "TEMPERATURA FUERA DEL RANGO DESEADO"
			FinSi
		FinSi
	FinSi
FinAlgoritmo
