Algoritmo FUNCIONAMIENTO_ASCENSOR_EJERCICIO1
	
	DEFINIR PISO COMO ENTERO
	
	ESCRIBIR "INGRESE EL PISO AL QUE DESEA IR"
	LEER PISO
	
	SI PISO >= 1 Y PISO <= 10 Entonces
		escribir "PISO CORRECTO, ASCENSOR EN MOVIMIENTO"
	SiNo
		SI PISO<= 0 Entonces
			ESCRIBIR "ERROR: PISO NO VALIDO"
		SiNo
			SI PISO >= 10
				ESCRIBIR " ERROR: PISO NO VALIDO"
			FinSi
		FinSi
	FinSi
	
FinAlgoritmo
