Algoritmo LIMITE_DE_PESO
	DEFINIR PESO Como Real
	DEFINIR PISO COMO ENTERO
	
	Escribir "INGRESE SU PESO: (KG)"
	LEER PESO
	
	SI PESO <= 80 Entonces
		Escribir "SELECCIONE EL PISO AL QUE DESEA IR: "
		LEER PISO
		ESCRIBIR "CANTIDAD DE PESO ADECUADA PARA EL ASCENSOR: ASCENSOR EN MOVIMIENTO"
	SiNo
		Escribir "ERROR: EL PESO EXCEDE LA CAPACIDAD DEL ASCENSOR"
	FinSi
	
FinAlgoritmo




